### ISSUE TITLE
Issue with binary

### ISSUE THREAD

**Issue by askmike1** [akamai/cli-cps#9]
I seem to have all the pre-reqs, but for this package I get the following
```
# akamai cps setup
  File "/root/.akamai-cli/src/cli-cps/bin/akamai-cps", line 240
    **arg,
```

**Comment by vreddhi** [comment]
Fixed in release v1.0.0

**Comment by askmike1** [comment]
@vreddhi I am using akamai version 1.0.2 and still having the same issues:

```
# akamai cps setup
  File "/root/.akamai-cli/src/cli-cps/bin/akamai-cps", line 260
    **arg,
         ^
SyntaxError: invalid syntax
```

**Comment by vreddhi** [comment]
@askmike1 Well the fix was in CPS package for CLI, and not the CLI itself

So you will have update the CPS package using:
`akamai update cps`

**Comment by askmike1** [comment]
@vreddhi 
```
# akamai upgrade
Checking for upgrades...... [OK]
Akamai CLI (v1.0.2) is already up-to-date

# akamai update cps
Attempting to update "cps" command...... [OK]
command "cps" already up-to-date

# akamai cps setup
  File "/root/.akamai-cli/src/cli-cps/bin/akamai-cps", line 260
    **arg,
         ^
SyntaxError: invalid syntax
```

**Comment by vreddhi** [comment]
It is surprising to me, as i do not see this issue in the 2 laptops of mine. May i ask you to try this:

`akamai cps uninstall`
`akamai cps install`

**Comment by askmike1** [comment]
No luck:

```
# akamai uninstall cps
Attempting to uninstall "cps" command...... [OK]

# akamai install cps
Attempting to fetch command from https://github.com/akamai/cli-cps.git...... [OK]
Installing...... [OK]

Installed Commands:

  auth
    Interface for Akamai Edgegrid Authentication
  config
    Manage configuration
  cps (alias: certs)
    Access Certificate Provisioning System (CPS) Information
  firewall (alias: fw)
    Access Akamai Firewall Rules Services, Subscriptions, and CIDRs
  site-shield (alias: ss)
    Access details of Site-Shield Maps, CIDRs and acknowledgement
  help
    Displays help information
  install (alias: get)
    Fetch and install packages from a Git repository.
  list
    Displays available commands
  snippets (aliases: pm, property-manager)
    Property Manager CLI for DevOps
  pipeline (aliases: pl, pipeline, pd, proddeploy)
    Akamai Pipeline for DevOps
  snippets (aliases: pm, property-manager)
    Property Manager CLI for DevOps
  pipeline (aliases: pl, pipeline, pd, proddeploy)
    Akamai Pipeline for DevOps
  property
    Manage configurations for Akamai properties
  purge
    Purge content from the Edge
  search
    Search for packages in the official Akamai CLI package repository
  firewall (alias: fw)
    Access Akamai Firewall Rules Services, Subscriptions, and CIDRs
  site-shield (alias: ss)
    Access details of Site-Shield Maps, CIDRs and acknowledgement
  snippets (aliases: pm, property-manager)
    Property Manager CLI for DevOps
  pipeline (aliases: pl, pipeline, pd, proddeploy)
    Akamai Pipeline for DevOps
  snippets (aliases: pm, property-manager)
    Property Manager CLI for DevOps
  pipeline (aliases: pl, pipeline, pd, proddeploy)
    Akamai Pipeline for DevOps
  uninstall
    Uninstall package containing <command>
  update
    Update one or more commands. If no command is specified, all commands are updated
  upgrade
    Upgrade Akamai CLI to the latest version
  visitor-prioritization (alias: vp)
    Access and control Visitor Prioritization cloudlet

See "akamai help [command]" for details.

# akamai cps setup
  File "/root/.akamai-cli/src/cli-cps/bin/akamai-cps", line 260
    **arg,
         ^
SyntaxError: invalid syntax
```

**Comment by askmike1** [comment]
When I open that akamai-cps file it says `PACKAGE_VERSION = "0.1.0"`

**Comment by aetsai** [comment]
ok, i am working with our cli team @dshafik on this.  His team is working on improving some of the debug and installation processes for this.  At this exact time, not sure why akamai cli seems to not be using your python3 version.  Do you have pyenv or virtual environments set up?  I think that's known to work work as well with our CLI.  Do you need python2 or is it possible to uninstall that so we are left with python3 then it should work

**Comment by askmike1** [comment]
using pyenv does seem to help here

**Comment by vreddhi** [comment]
@askmike1 Looks like its resolved using pyenv. Please re-open the issue if this is seen again.
